# Where should we write the GIF?
Output image/demo-member.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 40
Set Width 1500
Set Height 1200

# Type a command in the terminal.
Type "./schedule-ctl -m 梅西,C罗,科比,詹姆斯,乔丹,艾弗森,迪玛利亚,姆巴佩,内马尔"

# Run the command by pressing enter.
Enter
# Pause for dramatic effect...
Sleep 5s

Type "y"

Sleep 5s

Type "2"
Enter
Sleep 5s

Type "10"
# Run the command by pressing enter.
Enter


# Admire the output for a bit.
Sleep 10s