# Where should we write the GIF?
Output image/demo-file.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 40
Set Width 1200
Set Height 1200

# Type a command in the terminal.
Type "./schedule-ctl  -f list.txt"

# Run the command by pressing enter.
Enter
# Pause for dramatic effect...
Sleep 5s

Type "y"

Sleep 5s

Type "2"
Enter
Sleep 5s

Type "10"
Enter

# Run the command by pressing enter.

# Admire the output for a bit.
Sleep 10s